version: "3"
services:
  kafka-connect:
    container_name: kafka-connect
    image: 'bitnami/kafka:latest'
    volumes:
      - kafka-connect-data:/bitnami/kafka
      - ./config/connect-distributed.properties:/opt/bitnami/kafka/config/connect-distributed.properties
      - ./connectors:/opt/connectors
      - ./data:/data
    ports:
      - 8083:8083
    networks:
      - mykafka-net
    command: ['/opt/bitnami/kafka/bin/connect-distributed.sh', '/opt/bitnami/kafka/config/connect-distributed.properties']
  kafka-connect-ui:
    container_name: kafka-connect-ui
    image: landoop/kafka-connect-ui
    ports:
      - 8000:8000
    environment:
      CONNECT_URL: http://kafka-connect:8083
    networks:
      - mykafka-net
volumes:
  kafka-connect-data:
    driver: local
networks:
  # docker network create mykafka-net
  mykafka-net:
    external: true
