version: "3"
services:
  kafka-broker:
    container_name: kafka-broker
    image: 'bitnami/kafka:latest'
    volumes:
      - kafka-broker-data:/bitnami/kafka
    ports:
      - 9092:9092
      - 9094:9094
    environment:
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_KRAFT_CLUSTER_ID: 10HT3ErKTyKq9iXHk0EfBg
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-broker:9093
      # Use 2 IPs for 2 listeners - (1)
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,REPLICATION:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,REPLICATION://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,REPLICATION://192.168.1.3:9094
      # KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      # KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://195.168.1.5:9092
    networks:
      - mykafka-net
volumes:
  kafka-broker-data:
    driver: local
networks:
  # docker network create mykafka-net
  mykafka-net:
    external: true
