version: "3"
services:
  kafka-connect-ui:
    container_name: kafka-connect-ui
    image: landoop/kafka-connect-ui
    ports:
      - 8888:8000
    environment:
      CONNECT_URL: http://192.168.1.3:8083
    networks:
      - mykafka-net
networks:
  # docker network create mykafka-net
  mykafka-net:
    external: true
